apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd


resources:
- base/ingress-argo.yaml
- base/namespace.yaml
- base/bootstrapJeanKluser.yaml
# - base/rollouts-extension.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml

# components:
# - https://github.com/argoproj-labs/argocd-extensions/manifests

patches:
  - path: overlays/production/argo-cd-cm.yaml
  # - path: overlays/production/argocd-server-service.yaml
  # - path: overlays/production/argocd-repo-server-deploy.yaml
  # - path: overlays/production/argocd-notifications-controller-deploy.yaml
  # - path: overlays/production/argocd-notifications-cm.yaml
  - path: overlays/production/argocd-cmd-params-cm.yaml

  # - path: https://raw.githubusercontent.com/argoproj/argo-cd/master/notifications_catalog/install.yaml

commonLabels:
  app.kubernetes.io/instance: argocd
  app.kubernetes.io/part-of: argocd

# images:
# - name: quay.io/argoproj/argocd
#   newName: ghcr.io/argoproj/argo-cd/argocd
#   newTag: 2.9.0-ecbd24da