---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami2
  namespace: flux-system
spec:
  type: oci
  interval: 30m
  url: oci://registry-1.docker.io/bitnamicharts/
