apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-superuser
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "8"

spec:
  type: kv-v2

  # mount path
  mount: kv-v2

  # path of the secret
  path: postgresql/superuser

  # dest k8s secret
  destination:
    name: superuser-secret
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: pgsql-auth