---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometeus-stack
  namespace: &namespace observability
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 4m
  path: ./kubernetes/apps/observability/kube-prometeus-stack/app
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: deployment
      name: vault-agent-injector
      namespace: vault
  dependsOn:
    - name: vault-secrets-operator
      namespace: vault
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 4m
  wait: false