---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./tand-db-secret.yaml
  - ./tandoor-auth.yaml
  - ./tandoor-secret.yaml
configMapGenerator:
  - name: tandoor-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
